### ISSUE TITLE
Can't find javafx symbol after adding lines into gradle 

### ISSUE THREAD

**Issue by BryanYap972** [nus-cs2103-AY1920S2/forum#28] opened 2020-02-01 09:22 UTC
Encountering can't find symbol error for javafx import even after adding the necessary lines into build.gradle. 

Lines added into build.gradle:
plugins {
    id 'org.openjfx.javafxplugin' version '0.0.7'
}

javafx {
    version = "11.0.2"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

**Comment by mario7lorenzo** [comment] 2020-02-01 09:28
Hi! have you re-build the project in intelliJ after adding the necessary lines? I suspect you haven't build the project again, that causes the dependencies to be not detected.

**Comment by BryanYap972** [comment] 2020-02-01 10:14
> Hi! have you re-build the project in intelliJ after adding the necessary lines? I suspect you haven't build the project again, that causes the dependencies to be not detected.

Yup, I have rebuilt my project and still symbol not found for javafx.

**Comment by okkhoy** [comment] 2020-02-01 10:23
Did you do a `gradlew build`?

**Comment by BryanYap972** [comment] 2020-02-01 10:43
> Did you do a `gradlew build`?

Yup, tried that too. Build successful but still javafx symbol not found.

**Comment by mario7lorenzo** [comment] 2020-02-01 10:46
Can you show the screenshot of the full error message, as well as the relevant classes.

**Comment by DANamic** [comment] 2020-02-01 10:48
Hi @BryanYap972 - I believe you're missing the below lines in your **build.grade** file, specifically under `dependencies`:

```
repositories {
    mavenCentral()
}

dependencies {
    String javaFxVersion = '11'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}
```

Do make sure you have the updated **javaFxTutorialPart1.md** file from the `ui-gradle` branch!

**Comment by BryanYap972** [comment] 2020-02-01 10:50
> dependencies {
>     String javaFxVersion = '11'
> 
>     implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
>     implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
>     implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
>     implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
>     implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
>     implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
>     implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
>     implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
>     implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
>     implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
>     implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
>     implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
> }

Added those dependencies as well and build again. Still the same symbol not found for javafx.

**Comment by DANamic** [comment] 2020-02-01 10:53
Hmmm, have you changed your application declaration in the **build.gradle** file to point to your **Launcher.java** class now instead of the original **Main.java/Duke.java** file?

Example (original):
```
application {
    // Change this to your main class.
    mainClassName = "duke.main.Duke"
}
```

To now Launcher:
```
application {
    // Change this to your main class.
    mainClassName = "duke.main.Launcher"
}
```

**Comment by BryanYap972** [comment] 2020-02-01 13:55
> Can you show the screenshot of the full error message, as well as the relevant classes.




> Hmmm, have you changed your application declaration in the **build.gradle** file to point to your **Launcher.java** class now instead of the original **Main.java/Duke.java** file?
> 
> Example (original):
> 
> ```
> application {
>     // Change this to your main class.
>     mainClassName = "duke.main.Duke"
> }
> ```
> 
> To now Launcher:
> 
> ```
> application {
>     // Change this to your main class.
>     mainClassName = "duke.main.Launcher"
> }
> ```

I'm still only at the first step. Not even looking at launcher yet haha.

**Comment by BryanYap972** [comment] 2020-02-01 13:56
> Can you show the screenshot of the full error message, as well as the relevant classes.

<img width="1408" alt="Screenshot 2020-02-01 at 6 48 29 PM" src="https://user-images.githubusercontent.com/52154266/73593305-a31b0500-453d-11ea-854f-47da6fd6ef9c.png">
<img width="862" alt="Screenshot 2020-02-01 at 6 48 46 PM" src="https://user-images.githubusercontent.com/52154266/73593306-a44c3200-453d-11ea-93a9-4d46a7b0fa84.png">

**Comment by xCelestialPhoenix** [comment] 2020-02-02 06:18
Hi @BryanYap972, I compared my build.gradle with yours and only the mainClassName is different. So I guess it's not your gradle's problem. Have you tried following the non-gradle way yet? Perhaps including the necessary libraries will help. Good luck.

**Comment by BryanYap972** [comment] 2020-02-02 07:08
> Hi @BryanYap972, I compared my build.gradle with yours and only the mainClassName is different. So I guess it's not your gradle's problem. Have you tried following the non-gradle way yet? Perhaps including the necessary libraries will help. Good luck.

I know that the problem will go away if you follow the non-gradle way and download the sdk. But shouldn't the gradle way alone work? Kinda confusing if the gradle way alone no longer works.

**Comment by xCelestialPhoenix** [comment] 2020-02-02 07:10
Sometimes certain ways are not compatible because of the diversity of systems used. If one way doesn't work, we can only find another method to achieve what we want. I guess this is just part of life.
Btw, my gradle work as intended after doing the non-gradle way.  ¯\\_(ツ)_/¯

**Comment by okkhoy** [comment] 2020-02-02 07:27
Brute force method: 
Delete the `.gradle` folder in your project and in your users folder (e.g.,: `C:\users\<username>\.gradle`)
This will force Gradle to download the packages all over again and, in many cases, solves the problem.  
(Notice the dot (`.`) in the folder name? It is intentional! Don't delete the `gradle` folder in the repo)

**Comment by gerhean** [comment] 2020-02-02 14:00
Have you tried 
`gradlew clean`
then
`gradlew build`?

**Comment by eugenetyc** [comment] 2020-02-02 15:32
Sometimes it is due to the paths of the file. Do make sure your files are named correctly, and that IntelliJ did not shift them around, potentially causing renaming (since it's automatic). That's what happened to me personally.

**Comment by zhuhanming** [comment] 2020-02-03 01:41
I encountered the same issue yesterday and tried the suggestions in this thread to no avail. What worked for me in the end was simply changing the `mainClassName` in `build.gradle` to `duke.Launcher` and everything suddenly worked.

**Comment by Dban1** [comment] 2020-02-03 02:48
For me, I did gradlew build, then closed IntelliJ and opened it again and it worked

**Comment by aakanksha-rai** [comment] 2020-02-03 11:49
Hi Bryan, have you been able to solve the problem? I am getting the same error as you. I have tried the above suggestions but they don't work.

**Comment by BryanYap972** [comment] 2020-02-04 07:50
> Hi Bryan, have you been able to solve the problem? I am getting the same error as you. I have tried the above suggestions but they don't work.

Sftllr, yup solved it with the help of a friend using the brute force method.

**Comment by okkhoy** [comment] 2020-02-04 11:58
@BryanYap972 can you detail what brute force method you followed? It may help others facing this issue.

**Comment by BryanYap972** [comment] 2020-02-04 13:17
> @BryanYap972 can you detail what brute force method you followed? It may help others facing this issue.

1) Delete hidden gradle file in both duke folder and user directory (/User/urUsername/  for mac).
2) Go command line and clean and rebuild gradle (./gradlew clean then  ./gradlew build for mac).
3) Exit Intellij and reopen the project.
4) If everything goes well, there should be a prompt by Intellij to import the dependencies for javafx. Just click import for the prompt and should solve the symbol not found for javafx.

**Comment by BryanYap972** [comment] 2020-02-04 13:20
> > @BryanYap972 can you detail what brute force method you followed? It may help others facing this issue.
> 
> 1. Delete hidden gradle file in both duke folder and user directory (/User/urUsername/  for mac).
> 2. Go command line and clean and rebuild gradle (./gradlew clean then  ./gradlew build for mac).
> 3. Exit Intellij and reopen the project.
> 4. If everything goes well, there should be a prompt by Intellij to import the dependencies for javafx. Just click import for the prompt and should solve the symbol not found for javafx.

Also, for the stuff I included in the build.gradle file is the stuff from both versions of the tutorial. 
dependencies {
    String javaFxVersion = '11'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}

and

plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.7'
}

javafx {
    version = "11.0.2"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

**Closed as completed** 2020-02-04 13:26 UTC
Labels: type-HelpRequest :sos:
